export const diseases = [
  // ─── TOMATO ───
  {
    id: 'tomato-bacterial-spot',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Bacterial Spot',
    scientificName: 'Xanthomonas campestris',
    type: 'Bacterial',
    typeColor: '#f59e0b',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Bacterial spot causes dark, water-soaked lesions on leaves, stems, and fruits. It spreads rapidly in warm, wet conditions and can severely reduce plant yield.',
    symptoms: [
      'Small, dark brown to black water-soaked spots on leaves',
      'Yellow halo surrounding the spots',
      'Spots may merge to form large necrotic areas',
      'Raised, scab-like spots on fruits',
      'Premature leaf drop in severe cases',
    ],
    causes: [
      'Infection by Xanthomonas bacteria',
      'Warm temperatures between 25–30°C',
      'High humidity and wet weather',
      'Infected seeds or transplants',
      'Overhead irrigation spreading bacteria',
    ],
    treatment: [
      'Apply copper-based bactericides every 7–10 days',
      'Remove and destroy infected plant parts immediately',
      'Avoid overhead watering — use drip irrigation',
      'Rotate plants with non-host species for 2–3 years',
      'Use certified disease-free seeds',
    ],
    prevention: [
      'Use resistant tomato varieties',
      'Practice crop rotation annually',
      'Sanitize tools and equipment regularly',
      'Avoid working with plants when wet',
      'Improve air circulation between plants',
    ],
  },
  {
    id: 'tomato-early-blight',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Early Blight',
    scientificName: 'Alternaria solani',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Early blight is one of the most common fungal diseases in tomatoes. It primarily affects older leaves first, causing characteristic target-board shaped lesions.',
    symptoms: [
      'Dark brown spots with concentric rings (target-board pattern)',
      'Yellow area surrounding each spot',
      'Spots appear first on older, lower leaves',
      'Severely affected leaves turn yellow and drop',
      'Dark, sunken lesions may appear on stems',
    ],
    causes: [
      'Alternaria solani fungus in infected soil or debris',
      'Warm temperatures (24–29°C) with high humidity',
      'Extended periods of leaf wetness',
      'Nutritional deficiencies weakening the plant',
      'Dense planting reducing air circulation',
    ],
    treatment: [
      'Apply fungicides containing chlorothalonil or mancozeb',
      'Remove infected leaves and dispose of them away from garden',
      'Mulch around plants to prevent soil splash',
      'Ensure adequate fertilization especially nitrogen',
      'Space plants properly to improve air circulation',
    ],
    prevention: [
      'Use resistant or tolerant tomato varieties',
      'Water at the base of plants, not on leaves',
      'Remove plant debris at end of season',
      'Rotate tomatoes with unrelated plants',
      'Apply preventative fungicide sprays in wet weather',
    ],
  },
  {
    id: 'tomato-late-blight',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Late Blight',
    scientificName: 'Phytophthora infestans',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Critical',
    severityColor: '#dc2626',
    description: 'Late blight is a highly destructive disease that can destroy entire plants within days. It is the same pathogen responsible for the Irish potato famine of the 1840s.',
    symptoms: [
      'Pale green or yellow water-soaked spots on leaves',
      'White cottony mold on underside of leaves in humid weather',
      'Dark brown, greasy-looking lesions on stems',
      'Firm, brown, rough-textured rot on fruits',
      'Rapid collapse of entire plant in severe cases',
    ],
    causes: [
      'Phytophthora infestans water mold',
      'Cool temperatures (10–20°C) with high humidity',
      'Overhead watering or frequent rainfall',
      'Infected transplants or volunteer plants',
      'Wind-dispersed spores from nearby infected plants',
    ],
    treatment: [
      'Apply fungicides containing metalaxyl or chlorothalonil immediately',
      'Remove and bag all infected plant material',
      'Do not compost infected debris — destroy it',
      'Apply copper-based fungicide as a protective spray',
      'In severe cases, remove entire plant to prevent spread',
    ],
    prevention: [
      'Plant resistant varieties when available',
      'Avoid planting tomatoes near potatoes',
      'Ensure excellent drainage and air circulation',
      'Monitor plants daily during cool, wet weather',
      'Apply preventative fungicide sprays before symptoms appear',
    ],
  },
  {
    id: 'tomato-leaf-mold',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Leaf Mold',
    scientificName: 'Passalora fulva',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Tomato leaf mold thrives in high humidity environments, especially in greenhouses. It causes significant yield loss by reducing photosynthesis.',
    symptoms: [
      'Pale green or yellowish spots on upper leaf surface',
      'Olive-green to grayish-brown velvety mold on leaf underside',
      'Affected leaves curl, wither and drop prematurely',
      'Rarely affects fruits but may cause blossom end rot',
    ],
    causes: [
      'Passalora fulva fungus spores in air',
      'High relative humidity above 85%',
      'Poor air circulation in greenhouse settings',
      'Temperatures between 22–25°C',
    ],
    treatment: [
      'Apply fungicides such as chlorothalonil or mancozeb',
      'Reduce humidity by improving ventilation',
      'Remove and destroy affected leaves',
      'Avoid overhead watering',
    ],
    prevention: [
      'Use resistant tomato varieties',
      'Maintain humidity below 85% in greenhouses',
      'Space plants to maximize air circulation',
      'Regularly inspect undersides of leaves',
    ],
  },
  {
    id: 'tomato-mosaic-virus',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Mosaic Virus',
    scientificName: 'Tomato mosaic virus (ToMV)',
    type: 'Viral',
    typeColor: '#6366f1',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Tomato mosaic virus is a highly contagious viral disease that can persist in soil and plant debris for years. It significantly reduces fruit quality and yield.',
    symptoms: [
      'Mottled light and dark green mosaic pattern on leaves',
      'Leaves may be distorted, curled, or fern-like',
      'Stunted plant growth',
      'Fruits may show internal browning or uneven ripening',
      'Yellow streaking on young leaves',
    ],
    causes: [
      'Tomato mosaic virus spread by contact',
      'Contaminated hands, tools, or clothing',
      'Infected seed',
      'Tobacco products carrying related viruses',
    ],
    treatment: [
      'No cure exists — remove and destroy infected plants',
      'Disinfect all tools with 10% bleach solution',
      'Wash hands thoroughly before handling plants',
      'Control aphids which can spread related viruses',
    ],
    prevention: [
      'Use certified virus-free seeds',
      'Plant resistant varieties',
      'Do not smoke near plants',
      'Sanitize tools between plants',
      'Control insect vectors with appropriate pesticides',
    ],
  },

  // ─── POTATO ───
  {
    id: 'potato-early-blight',
    plant: 'Potato',
    plantIcon: '🥔',
    name: 'Early Blight',
    scientificName: 'Alternaria solani',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Potato early blight causes significant defoliation and tuber quality loss. Older leaves are affected first, with characteristic concentric ring lesions.',
    symptoms: [
      'Dark brown spots with concentric rings on older leaves',
      'Yellowing of surrounding leaf tissue',
      'Premature defoliation starting from lower leaves',
      'Dark, sunken lesions on tubers at harvest',
    ],
    causes: [
      'Alternaria solani fungus surviving in soil',
      'Warm, humid weather conditions',
      'Stressed or nutrient-deficient plants',
      'Infected plant debris from previous season',
    ],
    treatment: [
      'Apply mancozeb or chlorothalonil fungicide',
      'Remove and destroy infected foliage',
      'Ensure adequate nitrogen fertilization',
      'Avoid overhead irrigation',
    ],
    prevention: [
      'Use certified disease-free seed potatoes',
      'Rotate with non-host plants for 3 years',
      'Maintain proper plant nutrition',
      'Apply preventative fungicides during wet seasons',
    ],
  },
  {
    id: 'potato-late-blight',
    plant: 'Potato',
    plantIcon: '🥔',
    name: 'Late Blight',
    scientificName: 'Phytophthora infestans',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Critical',
    severityColor: '#dc2626',
    description: 'The most devastating potato disease in history. Late blight can destroy an entire field in days under favorable conditions.',
    symptoms: [
      'Water-soaked, pale green spots on leaves',
      'White mold on leaf undersides in humid conditions',
      'Dark brown, firm rot spreading through tubers',
      'Entire plant collapse in severe infections',
      'Foul smell from rotting tubers',
    ],
    causes: [
      'Phytophthora infestans pathogen',
      'Cool, moist weather (10–20°C)',
      'Infected seed potatoes',
      'Windborne spores from nearby infected fields',
    ],
    treatment: [
      'Apply metalaxyl-based fungicide immediately upon detection',
      'Destroy all infected plant material',
      'Do not store potentially infected tubers',
      'Apply copper hydroxide as protective spray',
    ],
    prevention: [
      'Plant only certified disease-free seed potatoes',
      'Use resistant varieties',
      'Apply preventative fungicide in wet conditions',
      'Monitor crops daily during cool wet weather',
    ],
  },

  // ─── ROSE ───
  {
    id: 'rose-black-spot',
    plant: 'Rose',
    plantIcon: '🌹',
    name: 'Black Spot',
    scientificName: 'Diplocarpon rosae',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Black spot is the most serious disease of roses worldwide. It causes progressive defoliation that weakens the plant and reduces flowering.',
    symptoms: [
      'Circular black spots with fringed margins on upper leaf surface',
      'Yellow discoloration surrounding the black spots',
      'Severely infected leaves turn completely yellow and fall',
      'Purple-red spots on young green stems',
      'Repeated defoliation weakens plant over time',
    ],
    causes: [
      'Diplocarpon rosae fungus',
      'Warm temperatures (18–24°C) and wet conditions',
      'Water splashing spores from soil to leaves',
      'Overhead watering keeping foliage wet',
      'Poor air circulation around plants',
    ],
    treatment: [
      'Apply fungicide containing myclobutanil or trifloxystrobin',
      'Remove all fallen leaves and infected foliage immediately',
      'Do not compost infected material',
      'Spray every 7–14 days during growing season',
      'Use baking soda spray (1 tsp per liter) as organic option',
    ],
    prevention: [
      'Plant disease-resistant rose varieties',
      'Water at base of plant, never on leaves',
      'Ensure good air circulation by pruning',
      'Apply mulch to prevent soil splash',
      'Begin preventative spraying in early spring',
    ],
  },
  {
    id: 'rose-powdery-mildew',
    plant: 'Rose',
    plantIcon: '🌹',
    name: 'Powdery Mildew',
    scientificName: 'Podosphaera pannosa',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Powdery mildew is easily recognizable by its white powdery coating on rose leaves, buds, and stems. It distorts new growth and reduces flowering.',
    symptoms: [
      'White powdery coating on young leaves, buds and stems',
      'New leaves and shoots distorted or curled',
      'Buds may fail to open properly',
      'Affected leaves may turn yellow and drop',
    ],
    causes: [
      'Podosphaera pannosa fungus spores in air',
      'Dry weather with high humidity',
      'Temperature fluctuations between day and night',
      'Overcrowded planting reducing air flow',
    ],
    treatment: [
      'Apply sulfur-based or systemic fungicide',
      'Spray with neem oil or potassium bicarbonate',
      'Remove and destroy heavily infected shoots',
      'Avoid excessive nitrogen fertilization',
    ],
    prevention: [
      'Choose mildew-resistant rose varieties',
      'Ensure good air circulation around plants',
      'Avoid overhead watering',
      'Prune to open up the plant center',
    ],
  },

  // ─── GRAPE ───
  {
    id: 'grape-black-rot',
    plant: 'Grape',
    plantIcon: '🍇',
    name: 'Black Rot',
    scientificName: 'Guignardia bidwellii',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Grape black rot can destroy entire fruit clusters. Infected berries shrivel into hard, mummified fruits that remain on the vine through winter.',
    symptoms: [
      'Tan or brown circular spots on leaves with dark borders',
      'Tiny black dots (pycnidia) visible within leaf spots',
      'Infected berries turn brown then shrivel into black mummies',
      'Black cankers on young shoots and tendrils',
    ],
    causes: [
      'Guignardia bidwellii fungus overwintering in mummified berries',
      'Warm, rainy spring weather (24–26°C)',
      'Spores released during rainfall splashing on plant tissue',
    ],
    treatment: [
      'Apply mancozeb or myclobutanil fungicide from bud break',
      'Remove and destroy all mummified berries',
      'Prune out infected canes during dormancy',
      'Spray at 10–14 day intervals during wet periods',
    ],
    prevention: [
      'Remove all overwintering inoculum (mummified fruit, infected canes)',
      'Improve air circulation through proper pruning and training',
      'Begin fungicide program at bud break',
      'Choose resistant grape varieties when possible',
    ],
  },

  // ─── APPLE ───
  {
    id: 'apple-scab',
    plant: 'Apple',
    plantIcon: '🍎',
    name: 'Apple Scab',
    scientificName: 'Venturia inaequalis',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Apple scab is the most economically important disease of apples worldwide. It significantly reduces fruit marketability and tree vigor.',
    symptoms: [
      'Olive-green to brown velvety spots on leaves',
      'Scab-like, dark, corky lesions on fruit surface',
      'Severely infected leaves curl and drop early',
      'Fruit lesions may crack, allowing secondary infections',
      'Distorted, stunted fruits in severe infections',
    ],
    causes: [
      'Venturia inaequalis fungus overwintering in fallen leaves',
      'Cool, wet spring weather (16–22°C)',
      'Spores released during rainfall in spring',
      'Extended periods of leaf wetness',
    ],
    treatment: [
      'Apply captan, myclobutanil, or thiophanate-methyl fungicide',
      'Begin spray program at green tip stage in spring',
      'Continue spraying every 7–14 days through petal fall',
      'Remove and destroy fallen infected leaves in autumn',
    ],
    prevention: [
      'Plant scab-resistant apple varieties',
      'Rake and destroy fallen leaves in autumn',
      'Prune for good air circulation',
      'Apply preventative fungicide program from early spring',
    ],
  },

  // ─── STRAWBERRY ───
  {
    id: 'strawberry-leaf-scorch',
    plant: 'Strawberry',
    plantIcon: '🍓',
    name: 'Leaf Scorch',
    scientificName: 'Diplocarpon earliana',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Strawberry leaf scorch causes dark purple spots that give leaves a scorched appearance, reducing photosynthesis and plant vigor.',
    symptoms: [
      'Small, irregular dark purple spots on upper leaf surface',
      'Spots enlarge and centers turn brown or gray',
      'Severely affected leaves look scorched or burned',
      'Reduced fruit size and yield in heavily infected plants',
    ],
    causes: [
      'Diplocarpon earliana fungus',
      'Warm, wet weather conditions',
      'Dense planting with poor air circulation',
      'Infected plant material used for propagation',
    ],
    treatment: [
      'Apply captan or myclobutanil fungicide',
      'Remove and destroy heavily infected leaves',
      'Renovate plantings after harvest by mowing foliage',
      'Thin planting to improve air circulation',
    ],
    prevention: [
      'Use certified disease-free planting stock',
      'Plant resistant varieties',
      'Avoid overhead irrigation',
      'Renovate strawberry beds annually after harvest',
    ],
  },

  // ─── CORN ───
  {
    id: 'corn-common-rust',
    plant: 'Corn',
    plantIcon: '🌽',
    name: 'Common Rust',
    scientificName: 'Puccinia sorghi',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Common rust appears as brick-red pustules scattered across corn leaves. While rarely fatal, severe infections can reduce yields significantly.',
    symptoms: [
      'Small, circular to elongated brick-red pustules on both leaf surfaces',
      'Pustules may be scattered or in dense groups',
      'In severe cases, pustules cover entire leaf',
      'Leaves may yellow and die in heavy infections',
    ],
    causes: [
      'Puccinia sorghi fungus spores blown by wind',
      'Cool temperatures (16–23°C) with high humidity',
      'Extended periods of heavy dew or light rain',
    ],
    treatment: [
      'Apply fungicide containing azoxystrobin or propiconazole if severe',
      'Treatment most effective before tasseling',
      'Scout fields regularly for early detection',
    ],
    prevention: [
      'Plant rust-resistant corn hybrids',
      'Plant early to avoid peak rust infection periods',
      'Monitor weather forecasts for favorable rust conditions',
    ],
  },
]

export const getByPlant = (plantName) =>
  diseases.filter(d => d.plant.toLowerCase() === plantName.toLowerCase())

export const getById = (id) =>
  diseases.find(d => d.id === id)

export const getAllPlants = () =>
  [...new Set(diseases.map(d => d.plant))]

export const getByType = (type) =>
  diseases.filter(d => d.type.toLowerCase() === type.toLowerCase())

export const getAllTypes = () =>
  [...new Set(diseases.map(d => d.type))]