// export const diseases = [
//   // ─── TOMATO ───
//   {
//     id: 'tomato-bacterial-spot',
//     plant: 'Tomato',
//     plantIcon: '🍅',
//     name: 'Bacterial Spot',
//     scientificName: 'Xanthomonas campestris',
//     type: 'Bacterial',
//     typeColor: '#f59e0b',
//     severity: 'High',
//     severityColor: '#ef4444',
//     description: 'Bacterial spot causes dark, water-soaked lesions on leaves, stems, and fruits. It spreads rapidly in warm, wet conditions and can severely reduce plant yield.',
//     symptoms: [
//       'Small, dark brown to black water-soaked spots on leaves',
//       'Yellow halo surrounding the spots',
//       'Spots may merge to form large necrotic areas',
//       'Raised, scab-like spots on fruits',
//       'Premature leaf drop in severe cases',
//     ],
//     causes: [
//       'Infection by Xanthomonas bacteria',
//       'Warm temperatures between 25–30°C',
//       'High humidity and wet weather',
//       'Infected seeds or transplants',
//       'Overhead irrigation spreading bacteria',
//     ],
//     treatment: [
//       'Apply copper-based bactericides every 7–10 days',
//       'Remove and destroy infected plant parts immediately',
//       'Avoid overhead watering — use drip irrigation',
//       'Rotate plants with non-host species for 2–3 years',
//       'Use certified disease-free seeds',
//     ],
//     prevention: [
//       'Use resistant tomato varieties',
//       'Practice crop rotation annually',
//       'Sanitize tools and equipment regularly',
//       'Avoid working with plants when wet',
//       'Improve air circulation between plants',
//     ],
//   },
//   {
//     id: 'tomato-early-blight',
//     plant: 'Tomato',
//     plantIcon: '🍅',
//     name: 'Early Blight',
//     scientificName: 'Alternaria solani',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Early blight is one of the most common fungal diseases in tomatoes. It primarily affects older leaves first, causing characteristic target-board shaped lesions.',
//     symptoms: [
//       'Dark brown spots with concentric rings (target-board pattern)',
//       'Yellow area surrounding each spot',
//       'Spots appear first on older, lower leaves',
//       'Severely affected leaves turn yellow and drop',
//       'Dark, sunken lesions may appear on stems',
//     ],
//     causes: [
//       'Alternaria solani fungus in infected soil or debris',
//       'Warm temperatures (24–29°C) with high humidity',
//       'Extended periods of leaf wetness',
//       'Nutritional deficiencies weakening the plant',
//       'Dense planting reducing air circulation',
//     ],
//     treatment: [
//       'Apply fungicides containing chlorothalonil or mancozeb',
//       'Remove infected leaves and dispose of them away from garden',
//       'Mulch around plants to prevent soil splash',
//       'Ensure adequate fertilization especially nitrogen',
//       'Space plants properly to improve air circulation',
//     ],
//     prevention: [
//       'Use resistant or tolerant tomato varieties',
//       'Water at the base of plants, not on leaves',
//       'Remove plant debris at end of season',
//       'Rotate tomatoes with unrelated plants',
//       'Apply preventative fungicide sprays in wet weather',
//     ],
//   },
//   {
//     id: 'tomato-late-blight',
//     plant: 'Tomato',
//     plantIcon: '🍅',
//     name: 'Late Blight',
//     scientificName: 'Phytophthora infestans',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Critical',
//     severityColor: '#dc2626',
//     description: 'Late blight is a highly destructive disease that can destroy entire plants within days. It is the same pathogen responsible for the Irish potato famine of the 1840s.',
//     symptoms: [
//       'Pale green or yellow water-soaked spots on leaves',
//       'White cottony mold on underside of leaves in humid weather',
//       'Dark brown, greasy-looking lesions on stems',
//       'Firm, brown, rough-textured rot on fruits',
//       'Rapid collapse of entire plant in severe cases',
//     ],
//     causes: [
//       'Phytophthora infestans water mold',
//       'Cool temperatures (10–20°C) with high humidity',
//       'Overhead watering or frequent rainfall',
//       'Infected transplants or volunteer plants',
//       'Wind-dispersed spores from nearby infected plants',
//     ],
//     treatment: [
//       'Apply fungicides containing metalaxyl or chlorothalonil immediately',
//       'Remove and bag all infected plant material',
//       'Do not compost infected debris — destroy it',
//       'Apply copper-based fungicide as a protective spray',
//       'In severe cases, remove entire plant to prevent spread',
//     ],
//     prevention: [
//       'Plant resistant varieties when available',
//       'Avoid planting tomatoes near potatoes',
//       'Ensure excellent drainage and air circulation',
//       'Monitor plants daily during cool, wet weather',
//       'Apply preventative fungicide sprays before symptoms appear',
//     ],
//   },
//   {
//     id: 'tomato-leaf-mold',
//     plant: 'Tomato',
//     plantIcon: '🍅',
//     name: 'Leaf Mold',
//     scientificName: 'Passalora fulva',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Tomato leaf mold thrives in high humidity environments, especially in greenhouses. It causes significant yield loss by reducing photosynthesis.',
//     symptoms: [
//       'Pale green or yellowish spots on upper leaf surface',
//       'Olive-green to grayish-brown velvety mold on leaf underside',
//       'Affected leaves curl, wither and drop prematurely',
//       'Rarely affects fruits but may cause blossom end rot',
//     ],
//     causes: [
//       'Passalora fulva fungus spores in air',
//       'High relative humidity above 85%',
//       'Poor air circulation in greenhouse settings',
//       'Temperatures between 22–25°C',
//     ],
//     treatment: [
//       'Apply fungicides such as chlorothalonil or mancozeb',
//       'Reduce humidity by improving ventilation',
//       'Remove and destroy affected leaves',
//       'Avoid overhead watering',
//     ],
//     prevention: [
//       'Use resistant tomato varieties',
//       'Maintain humidity below 85% in greenhouses',
//       'Space plants to maximize air circulation',
//       'Regularly inspect undersides of leaves',
//     ],
//   },
//   {
//     id: 'tomato-mosaic-virus',
//     plant: 'Tomato',
//     plantIcon: '🍅',
//     name: 'Mosaic Virus',
//     scientificName: 'Tomato mosaic virus (ToMV)',
//     type: 'Viral',
//     typeColor: '#6366f1',
//     severity: 'High',
//     severityColor: '#ef4444',
//     description: 'Tomato mosaic virus is a highly contagious viral disease that can persist in soil and plant debris for years. It significantly reduces fruit quality and yield.',
//     symptoms: [
//       'Mottled light and dark green mosaic pattern on leaves',
//       'Leaves may be distorted, curled, or fern-like',
//       'Stunted plant growth',
//       'Fruits may show internal browning or uneven ripening',
//       'Yellow streaking on young leaves',
//     ],
//     causes: [
//       'Tomato mosaic virus spread by contact',
//       'Contaminated hands, tools, or clothing',
//       'Infected seed',
//       'Tobacco products carrying related viruses',
//     ],
//     treatment: [
//       'No cure exists — remove and destroy infected plants',
//       'Disinfect all tools with 10% bleach solution',
//       'Wash hands thoroughly before handling plants',
//       'Control aphids which can spread related viruses',
//     ],
//     prevention: [
//       'Use certified virus-free seeds',
//       'Plant resistant varieties',
//       'Do not smoke near plants',
//       'Sanitize tools between plants',
//       'Control insect vectors with appropriate pesticides',
//     ],
//   },

//   // ─── POTATO ───
//   {
//     id: 'potato-early-blight',
//     plant: 'Potato',
//     plantIcon: '🥔',
//     name: 'Early Blight',
//     scientificName: 'Alternaria solani',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Potato early blight causes significant defoliation and tuber quality loss. Older leaves are affected first, with characteristic concentric ring lesions.',
//     symptoms: [
//       'Dark brown spots with concentric rings on older leaves',
//       'Yellowing of surrounding leaf tissue',
//       'Premature defoliation starting from lower leaves',
//       'Dark, sunken lesions on tubers at harvest',
//     ],
//     causes: [
//       'Alternaria solani fungus surviving in soil',
//       'Warm, humid weather conditions',
//       'Stressed or nutrient-deficient plants',
//       'Infected plant debris from previous season',
//     ],
//     treatment: [
//       'Apply mancozeb or chlorothalonil fungicide',
//       'Remove and destroy infected foliage',
//       'Ensure adequate nitrogen fertilization',
//       'Avoid overhead irrigation',
//     ],
//     prevention: [
//       'Use certified disease-free seed potatoes',
//       'Rotate with non-host plants for 3 years',
//       'Maintain proper plant nutrition',
//       'Apply preventative fungicides during wet seasons',
//     ],
//   },
//   {
//     id: 'potato-late-blight',
//     plant: 'Potato',
//     plantIcon: '🥔',
//     name: 'Late Blight',
//     scientificName: 'Phytophthora infestans',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Critical',
//     severityColor: '#dc2626',
//     description: 'The most devastating potato disease in history. Late blight can destroy an entire field in days under favorable conditions.',
//     symptoms: [
//       'Water-soaked, pale green spots on leaves',
//       'White mold on leaf undersides in humid conditions',
//       'Dark brown, firm rot spreading through tubers',
//       'Entire plant collapse in severe infections',
//       'Foul smell from rotting tubers',
//     ],
//     causes: [
//       'Phytophthora infestans pathogen',
//       'Cool, moist weather (10–20°C)',
//       'Infected seed potatoes',
//       'Windborne spores from nearby infected fields',
//     ],
//     treatment: [
//       'Apply metalaxyl-based fungicide immediately upon detection',
//       'Destroy all infected plant material',
//       'Do not store potentially infected tubers',
//       'Apply copper hydroxide as protective spray',
//     ],
//     prevention: [
//       'Plant only certified disease-free seed potatoes',
//       'Use resistant varieties',
//       'Apply preventative fungicide in wet conditions',
//       'Monitor crops daily during cool wet weather',
//     ],
//   },

//   // ─── ROSE ───
//   {
//     id: 'rose-black-spot',
//     plant: 'Rose',
//     plantIcon: '🌹',
//     name: 'Black Spot',
//     scientificName: 'Diplocarpon rosae',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'High',
//     severityColor: '#ef4444',
//     description: 'Black spot is the most serious disease of roses worldwide. It causes progressive defoliation that weakens the plant and reduces flowering.',
//     symptoms: [
//       'Circular black spots with fringed margins on upper leaf surface',
//       'Yellow discoloration surrounding the black spots',
//       'Severely infected leaves turn completely yellow and fall',
//       'Purple-red spots on young green stems',
//       'Repeated defoliation weakens plant over time',
//     ],
//     causes: [
//       'Diplocarpon rosae fungus',
//       'Warm temperatures (18–24°C) and wet conditions',
//       'Water splashing spores from soil to leaves',
//       'Overhead watering keeping foliage wet',
//       'Poor air circulation around plants',
//     ],
//     treatment: [
//       'Apply fungicide containing myclobutanil or trifloxystrobin',
//       'Remove all fallen leaves and infected foliage immediately',
//       'Do not compost infected material',
//       'Spray every 7–14 days during growing season',
//       'Use baking soda spray (1 tsp per liter) as organic option',
//     ],
//     prevention: [
//       'Plant disease-resistant rose varieties',
//       'Water at base of plant, never on leaves',
//       'Ensure good air circulation by pruning',
//       'Apply mulch to prevent soil splash',
//       'Begin preventative spraying in early spring',
//     ],
//   },
//   {
//     id: 'rose-powdery-mildew',
//     plant: 'Rose',
//     plantIcon: '🌹',
//     name: 'Powdery Mildew',
//     scientificName: 'Podosphaera pannosa',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Powdery mildew is easily recognizable by its white powdery coating on rose leaves, buds, and stems. It distorts new growth and reduces flowering.',
//     symptoms: [
//       'White powdery coating on young leaves, buds and stems',
//       'New leaves and shoots distorted or curled',
//       'Buds may fail to open properly',
//       'Affected leaves may turn yellow and drop',
//     ],
//     causes: [
//       'Podosphaera pannosa fungus spores in air',
//       'Dry weather with high humidity',
//       'Temperature fluctuations between day and night',
//       'Overcrowded planting reducing air flow',
//     ],
//     treatment: [
//       'Apply sulfur-based or systemic fungicide',
//       'Spray with neem oil or potassium bicarbonate',
//       'Remove and destroy heavily infected shoots',
//       'Avoid excessive nitrogen fertilization',
//     ],
//     prevention: [
//       'Choose mildew-resistant rose varieties',
//       'Ensure good air circulation around plants',
//       'Avoid overhead watering',
//       'Prune to open up the plant center',
//     ],
//   },

//   // ─── GRAPE ───
//   {
//     id: 'grape-black-rot',
//     plant: 'Grape',
//     plantIcon: '🍇',
//     name: 'Black Rot',
//     scientificName: 'Guignardia bidwellii',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'High',
//     severityColor: '#ef4444',
//     description: 'Grape black rot can destroy entire fruit clusters. Infected berries shrivel into hard, mummified fruits that remain on the vine through winter.',
//     symptoms: [
//       'Tan or brown circular spots on leaves with dark borders',
//       'Tiny black dots (pycnidia) visible within leaf spots',
//       'Infected berries turn brown then shrivel into black mummies',
//       'Black cankers on young shoots and tendrils',
//     ],
//     causes: [
//       'Guignardia bidwellii fungus overwintering in mummified berries',
//       'Warm, rainy spring weather (24–26°C)',
//       'Spores released during rainfall splashing on plant tissue',
//     ],
//     treatment: [
//       'Apply mancozeb or myclobutanil fungicide from bud break',
//       'Remove and destroy all mummified berries',
//       'Prune out infected canes during dormancy',
//       'Spray at 10–14 day intervals during wet periods',
//     ],
//     prevention: [
//       'Remove all overwintering inoculum (mummified fruit, infected canes)',
//       'Improve air circulation through proper pruning and training',
//       'Begin fungicide program at bud break',
//       'Choose resistant grape varieties when possible',
//     ],
//   },

//   // ─── APPLE ───
//   {
//     id: 'apple-scab',
//     plant: 'Apple',
//     plantIcon: '🍎',
//     name: 'Apple Scab',
//     scientificName: 'Venturia inaequalis',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'High',
//     severityColor: '#ef4444',
//     description: 'Apple scab is the most economically important disease of apples worldwide. It significantly reduces fruit marketability and tree vigor.',
//     symptoms: [
//       'Olive-green to brown velvety spots on leaves',
//       'Scab-like, dark, corky lesions on fruit surface',
//       'Severely infected leaves curl and drop early',
//       'Fruit lesions may crack, allowing secondary infections',
//       'Distorted, stunted fruits in severe infections',
//     ],
//     causes: [
//       'Venturia inaequalis fungus overwintering in fallen leaves',
//       'Cool, wet spring weather (16–22°C)',
//       'Spores released during rainfall in spring',
//       'Extended periods of leaf wetness',
//     ],
//     treatment: [
//       'Apply captan, myclobutanil, or thiophanate-methyl fungicide',
//       'Begin spray program at green tip stage in spring',
//       'Continue spraying every 7–14 days through petal fall',
//       'Remove and destroy fallen infected leaves in autumn',
//     ],
//     prevention: [
//       'Plant scab-resistant apple varieties',
//       'Rake and destroy fallen leaves in autumn',
//       'Prune for good air circulation',
//       'Apply preventative fungicide program from early spring',
//     ],
//   },

//   // ─── STRAWBERRY ───
//   {
//     id: 'strawberry-leaf-scorch',
//     plant: 'Strawberry',
//     plantIcon: '🍓',
//     name: 'Leaf Scorch',
//     scientificName: 'Diplocarpon earliana',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Strawberry leaf scorch causes dark purple spots that give leaves a scorched appearance, reducing photosynthesis and plant vigor.',
//     symptoms: [
//       'Small, irregular dark purple spots on upper leaf surface',
//       'Spots enlarge and centers turn brown or gray',
//       'Severely affected leaves look scorched or burned',
//       'Reduced fruit size and yield in heavily infected plants',
//     ],
//     causes: [
//       'Diplocarpon earliana fungus',
//       'Warm, wet weather conditions',
//       'Dense planting with poor air circulation',
//       'Infected plant material used for propagation',
//     ],
//     treatment: [
//       'Apply captan or myclobutanil fungicide',
//       'Remove and destroy heavily infected leaves',
//       'Renovate plantings after harvest by mowing foliage',
//       'Thin planting to improve air circulation',
//     ],
//     prevention: [
//       'Use certified disease-free planting stock',
//       'Plant resistant varieties',
//       'Avoid overhead irrigation',
//       'Renovate strawberry beds annually after harvest',
//     ],
//   },

//   // ─── CORN ───
//   {
//     id: 'corn-common-rust',
//     plant: 'Corn',
//     plantIcon: '🌽',
//     name: 'Common Rust',
//     scientificName: 'Puccinia sorghi',
//     type: 'Fungal',
//     typeColor: '#8b5cf6',
//     severity: 'Medium',
//     severityColor: '#f59e0b',
//     description: 'Common rust appears as brick-red pustules scattered across corn leaves. While rarely fatal, severe infections can reduce yields significantly.',
//     symptoms: [
//       'Small, circular to elongated brick-red pustules on both leaf surfaces',
//       'Pustules may be scattered or in dense groups',
//       'In severe cases, pustules cover entire leaf',
//       'Leaves may yellow and die in heavy infections',
//     ],
//     causes: [
//       'Puccinia sorghi fungus spores blown by wind',
//       'Cool temperatures (16–23°C) with high humidity',
//       'Extended periods of heavy dew or light rain',
//     ],
//     treatment: [
//       'Apply fungicide containing azoxystrobin or propiconazole if severe',
//       'Treatment most effective before tasseling',
//       'Scout fields regularly for early detection',
//     ],
//     prevention: [
//       'Plant rust-resistant corn hybrids',
//       'Plant early to avoid peak rust infection periods',
//       'Monitor weather forecasts for favorable rust conditions',
//     ],
//   },
// ]

// export const getByPlant = (plantName) =>
//   diseases.filter(d => d.plant.toLowerCase() === plantName.toLowerCase())

// export const getById = (id) =>
//   diseases.find(d => d.id === id)

// export const getAllPlants = () =>
//   [...new Set(diseases.map(d => d.plant))]

// export const getByType = (type) =>
//   diseases.filter(d => d.type.toLowerCase() === type.toLowerCase())

// export const getAllTypes = () =>
//   [...new Set(diseases.map(d => d.type))]


export const diseases = [
  // ─── APPLE ───
  {
    id: 'apple-apple-scab',
    plant: 'Apple',
    plantIcon: '🍎',
    name: 'Apple Scab',
    scientificName: 'Venturia inaequalis',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Apple scab causes olive-green to brown velvety spots on leaves and fruit, reducing fruit quality and tree vigor.',
    symptoms: [
      'Olive-green to dark brown velvety spots on leaves',
      'Scab-like, dark corky lesions on fruit surface',
      'Severely infected leaves curl and drop early',
      'Fruit may crack and become deformed',
    ],
    causes: [
      'Venturia inaequalis fungus overwintering in fallen leaves',
      'Cool, wet spring weather',
      'Extended periods of leaf wetness',
    ],
    treatment: [
      'Apply fungicides containing captan or myclobutanil',
      'Remove and destroy fallen infected leaves in autumn',
      'Prune trees for better air circulation',
    ],
    prevention: [
      'Plant scab-resistant apple varieties',
      'Rake and destroy fallen leaves',
      'Apply preventative fungicide program from early spring',
    ],
  },
  {
    id: 'apple-black-rot',
    plant: 'Apple',
    plantIcon: '🍎',
    name: 'Black Rot',
    scientificName: 'Botryosphaeria obtusa',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Black rot causes fruit rot, leaf spots, and cankers on branches, potentially killing the tree over time.',
    symptoms: [
      'Purple spots on leaves that enlarge with brown centers',
      'Fruit develops firm, brown rot that eventually blackens',
      'Sunken cankers on branches and trunk',
      'Fruit mummifies and remains on tree',
    ],
    causes: [
      'Botryosphaeria obtusa fungus',
      'Warm, humid conditions',
      'Spores spread by rain and wind',
      'Infected dead wood on tree',
    ],
    treatment: [
      'Prune out all cankered branches',
      'Remove mummified fruit from tree',
      'Apply fungicides during growing season',
      'Maintain tree vigor with proper fertilization',
    ],
    prevention: [
      'Prune dead wood regularly',
      'Avoid wounding trees',
      'Plant resistant varieties when available',
      'Apply dormant oil in early spring',
    ],
  },
  {
    id: 'apple-cedar-apple-rust',
    plant: 'Apple',
    plantIcon: '🍎',
    name: 'Cedar Apple Rust',
    scientificName: 'Gymnosporangium juniperi-virginianae',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Cedar apple rust requires both apple trees and cedar/juniper trees to complete its life cycle.',
    symptoms: [
      'Bright yellow to orange spots on upper leaf surface',
      'Small cup-like structures on leaf undersides',
      'Spots on fruit similar to leaves',
      'Premature defoliation in severe cases',
    ],
    causes: [
      'Fungus alternating between apple and cedar/juniper trees',
      'Warm, wet spring weather',
      'Spores traveling from nearby cedar trees',
    ],
    treatment: [
      'Apply fungicides at pink bud stage through petal fall',
      'Remove nearby cedar trees if possible',
      'Remove galls from cedar trees in winter',
    ],
    prevention: [
      'Plant apple trees at least 1/2 mile from cedar trees',
      'Use resistant apple varieties',
      'Apply preventative fungicide program',
    ],
  },
  {
    id: 'apple-healthy',
    plant: 'Apple',
    plantIcon: '🍎',
    name: 'Healthy Apple Tree',
    scientificName: 'Malus domestica',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Great news! Your apple tree appears to be healthy with no signs of disease.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plant is well-maintained and disease-free'],
    treatment: ['Continue regular maintenance and monitoring'],
    prevention: ['Maintain good cultural practices and monitor regularly'],
  },

  // ─── BLUEBERRY ───
  {
    id: 'blueberry-healthy',
    plant: 'Blueberry',
    plantIcon: '🍇',
    name: 'Healthy Blueberry',
    scientificName: 'Vaccinium corymbosum',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your blueberry plant appears healthy with no disease symptoms detected.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plant is well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Maintain proper soil pH and watering practices'],
  },

  // ─── CHERRY ───
  {
    id: 'cherry-powdery-mildew',
    plant: 'Cherry',
    plantIcon: '🍒',
    name: 'Powdery Mildew',
    scientificName: 'Podosphaera clandestina',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Powdery mildew appears as white powdery coating on cherry leaves, reducing photosynthesis and tree vigor.',
    symptoms: [
      'White powdery coating on leaf surfaces',
      'Leaves may curl and become distorted',
      'Stunted growth of young shoots',
      'Premature leaf drop in severe cases',
    ],
    causes: [
      'Fungus spores in humid conditions',
      'Poor air circulation around tree',
      'Warm days and cool nights',
      'Excessive nitrogen fertilization',
    ],
    treatment: [
      'Apply sulfur-based or potassium bicarbonate fungicide',
      'Prune to improve air circulation',
      'Remove severely infected shoots',
      'Apply neem oil as organic treatment',
    ],
    prevention: [
      'Plant resistant cherry varieties',
      'Avoid overhead watering',
      'Prune trees annually for good airflow',
      'Apply preventative fungicide in humid conditions',
    ],
  },
  {
    id: 'cherry-healthy',
    plant: 'Cherry',
    plantIcon: '🍒',
    name: 'Healthy Cherry Tree',
    scientificName: 'Prunus avium',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your cherry tree appears healthy with no signs of disease.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Tree is well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Maintain good cultural practices'],
  },

  // ─── CORN ───
  {
    id: 'corn-cercospora-leaf-spot',
    plant: 'Corn',
    plantIcon: '🌽',
    name: 'Gray Leaf Spot',
    scientificName: 'Cercospora zeae-maydis',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Gray leaf spot is a serious fungal disease that can cause significant yield loss in corn.',
    symptoms: [
      'Small, brown spots that become rectangular with parallel sides',
      'Spots turn gray with yellow halos',
      'Lesions develop between leaf veins',
      'Severe infection causes leaf blighting',
    ],
    causes: [
      'Cercospora zeae-maydis fungus',
      'Warm, humid conditions',
      'Continuous corn planting',
      'Infected crop residue on soil surface',
    ],
    treatment: [
      'Apply fungicides containing strobilurins or triazoles',
      'Tillage to bury crop residue',
      'Rotate corn with non-host crops',
    ],
    prevention: [
      'Plant resistant corn hybrids',
      'Crop rotation with soybeans or other crops',
      'Monitor fields during tasseling',
    ],
  },
  {
    id: 'corn-common-rust',
    plant: 'Corn',
    plantIcon: '🌽',
    name: 'Common Rust',
    scientificName: 'Puccinia sorghi',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Common rust appears as brick-red pustules on corn leaves, which can reduce yields in severe cases.',
    symptoms: [
      'Brick-red to brown pustules on leaf surfaces',
      'Pustules rupture releasing orange spores',
      'Severe infections cause leaf death',
      'Stunted growth in heavily infected plants',
    ],
    causes: [
      'Puccinia sorghi fungus spread by wind',
      'Cool to moderate temperatures with high humidity',
      'Spores traveling from southern regions',
    ],
    treatment: [
      'Apply fungicide containing azoxystrobin or propiconazole',
      'Early treatment most effective',
      'Use resistant hybrids',
    ],
    prevention: [
      'Plant rust-resistant corn hybrids',
      'Early planting to avoid peak rust season',
      'Scout fields regularly',
    ],
  },
  {
    id: 'corn-northern-leaf-blight',
    plant: 'Corn',
    plantIcon: '🌽',
    name: 'Northern Leaf Blight',
    scientificName: 'Exserohilum turcicum',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Northern leaf blight causes long cigar-shaped lesions that can rapidly destroy corn leaves.',
    symptoms: [
      'Long, elliptical gray-green lesions on lower leaves',
      'Lesions become tan with dark borders',
      'Lesions may merge killing entire leaves',
      'Reduced kernel fill and yield loss',
    ],
    causes: [
      'Exserohilum turcicum fungus',
      'Cool, humid conditions with heavy dew',
      'Continuous corn planting',
      'Infected crop residue',
    ],
    treatment: [
      'Apply fungicides at tasseling',
      'Rotate to non-host crops',
      'Bury residue with tillage',
    ],
    prevention: [
      'Plant resistant hybrids',
      'Practice crop rotation',
      'Avoid overhead irrigation',
    ],
  },
  {
    id: 'corn-healthy',
    plant: 'Corn',
    plantIcon: '🌽',
    name: 'Healthy Corn',
    scientificName: 'Zea mays',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your corn plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Practice good crop rotation and field sanitation'],
  },

  // ─── GRAPE ───
  {
    id: 'grape-black-rot',
    plant: 'Grape',
    plantIcon: '🍇',
    name: 'Black Rot',
    scientificName: 'Guignardia bidwellii',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Grape black rot can destroy entire fruit clusters, turning berries into hard black mummies.',
    symptoms: [
      'Brown circular spots on leaves with dark borders',
      'Black pimple-like structures in leaf spots',
      'Infected berries shrivel into black mummies',
      'Dark cankers on shoots and tendrils',
    ],
    causes: [
      'Guignardia bidwellii fungus',
      'Warm, rainy spring weather',
      'Spores released during rainfall',
    ],
    treatment: [
      'Apply mancozeb or myclobutanil fungicide',
      'Remove and destroy mummified berries',
      'Prune out infected canes',
    ],
    prevention: [
      'Remove overwintering mummies and infected canes',
      'Improve air circulation through pruning',
      'Begin fungicide program at bud break',
    ],
  },
  {
    id: 'grape-esca',
    plant: 'Grape',
    plantIcon: '🍇',
    name: 'Esca (Black Measles)',
    scientificName: 'Phaeomoniella chlamydospora',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Esca is a trunk disease causing leaf discoloration and fruit rot, progressively killing vines over time.',
    symptoms: [
      'Tiger-stripe pattern on leaves with tan and brown tissue',
      'Small black spots on fruit (black measles)',
      'White rot in trunk and cordons',
      'Vines collapse and die over years',
    ],
    causes: [
      'Several fungi infecting through pruning wounds',
      'Older vines more susceptible',
      'Poor wound healing after pruning',
    ],
    treatment: [
      'No effective cure - remove severely infected vines',
      'Surgery to remove decayed wood',
      'Protect pruning wounds with fungicide',
    ],
    prevention: [
      'Use clean planting material',
      'Protect pruning wounds immediately',
      'Remove infected vines promptly',
      'Avoid large pruning cuts',
    ],
  },
  {
    id: 'grape-leaf-blight',
    plant: 'Grape',
    plantIcon: '🍇',
    name: 'Leaf Blight',
    scientificName: 'Isariopsis leaf spot',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Leaf blight causes angular spots that can lead to premature defoliation of grapevines.',
    symptoms: [
      'Angular, reddish-brown spots on leaves',
      'Spots limited by leaf veins',
      'Severe infections cause leaf drop',
      'Reduced fruit quality and ripening',
    ],
    causes: [
      'Isariopsis fungus',
      'Warm, humid conditions',
      'Dense canopy with poor airflow',
    ],
    treatment: [
      'Apply fungicides containing mancozeb',
      'Remove and destroy infected leaves',
      'Improve canopy air circulation',
    ],
    prevention: [
      'Prune for open canopy',
      'Avoid overhead watering',
      'Apply preventative fungicide in wet seasons',
    ],
  },
  {
    id: 'grape-healthy',
    plant: 'Grape',
    plantIcon: '🍇',
    name: 'Healthy Grapevine',
    scientificName: 'Vitis vinifera',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your grapevines appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Vines are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Maintain good canopy management and sanitation'],
  },

  // ─── ORANGE ───
  {
    id: 'orange-citrus-greening',
    plant: 'Orange',
    plantIcon: '🍊',
    name: 'Citrus Greening (Huanglongbing)',
    scientificName: 'Candidatus Liberibacter asiaticus',
    type: 'Bacterial',
    typeColor: '#f59e0b',
    severity: 'Critical',
    severityColor: '#dc2626',
    description: 'Citrus greening is the most devastating citrus disease worldwide, with no cure once infected.',
    symptoms: [
      'Yellow shoots among green canopy',
      'Mottled, blotchy yellow leaves',
      'Small, lopsided fruit that stays green',
      'Bitter, inedible fruit quality',
      'Tree decline and death within years',
    ],
    causes: [
      'Bacteria spread by Asian citrus psyllid',
      'Infected nursery trees',
      'Grafting infected budwood',
    ],
    treatment: [
      'No cure - remove infected trees immediately',
      'Control psyllid vectors with insecticides',
      'Use certified disease-free trees for replanting',
    ],
    prevention: [
      'Plant certified disease-free trees',
      'Monitor for psyllids regularly',
      'Remove infected trees promptly',
      'Maintain strict area-wide management program',
    ],
  },

  // ─── PEACH ───
  {
    id: 'peach-bacterial-spot',
    plant: 'Peach',
    plantIcon: '🍑',
    name: 'Bacterial Spot',
    scientificName: 'Xanthomonas arboricola',
    type: 'Bacterial',
    typeColor: '#f59e0b',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Bacterial spot causes fruit blemishes and defoliation, reducing fruit quality and tree health.',
    symptoms: [
      'Small water-soaked spots on leaves',
      'Spots become angular and purple-black',
      'Lesions may drop out leaving shot-hole appearance',
      'Reddish spots on fruit with cracked skin',
    ],
    causes: [
      'Xanthomonas bacteria in spring',
      'Warm, wet conditions',
      'Wind-driven rain spreading bacteria',
    ],
    treatment: [
      'Apply copper-based bactericide',
      'Avoid overhead irrigation',
      'Prune to improve air circulation',
    ],
    prevention: [
      'Plant resistant peach varieties',
      'Apply dormant copper spray in winter',
      'Remove infected leaves and fruit',
    ],
  },
  {
    id: 'peach-healthy',
    plant: 'Peach',
    plantIcon: '🍑',
    name: 'Healthy Peach Tree',
    scientificName: 'Prunus persica',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your peach tree appears healthy with no signs of disease.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Tree is well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Maintain good cultural practices'],
  },

  // ─── PEPPER ───
  {
    id: 'pepper-bacterial-spot',
    plant: 'Pepper',
    plantIcon: '🌶️',
    name: 'Bacterial Spot',
    scientificName: 'Xanthomonas campestris',
    type: 'Bacterial',
    typeColor: '#f59e0b',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Bacterial spot is a serious disease of peppers causing defoliation and fruit spots.',
    symptoms: [
      'Small water-soaked spots on leaves',
      'Spots turn brown with yellow halos',
      'Defoliation in severe infections',
      'Raised scab-like spots on fruit',
    ],
    causes: [
      'Xanthomonas bacteria',
      'Warm, humid weather',
      'Overhead irrigation',
      'Infected seeds or transplants',
    ],
    treatment: [
      'Apply copper-based bactericide',
      'Remove infected plants',
      'Avoid working in wet foliage',
    ],
    prevention: [
      'Use disease-free seeds',
      'Rotate peppers with unrelated crops for 2 years',
      'Avoid overhead watering',
    ],
  },
  {
    id: 'pepper-healthy',
    plant: 'Pepper',
    plantIcon: '🌶️',
    name: 'Healthy Pepper',
    scientificName: 'Capsicum annuum',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your pepper plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Practice good garden sanitation'],
  },

  // ─── POTATO ───
  {
    id: 'potato-early-blight',
    plant: 'Potato',
    plantIcon: '🥔',
    name: 'Early Blight',
    scientificName: 'Alternaria solani',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Early blight causes dark concentric spots on potato leaves, leading to yield loss.',
    symptoms: [
      'Dark brown spots with concentric rings',
      'Yellowing around spots',
      'Defoliation starting on lower leaves',
      'Dark lesions on tubers at harvest',
    ],
    causes: [
      'Alternaria solani fungus',
      'Warm, humid weather',
      'Stressed or nutrient-deficient plants',
    ],
    treatment: [
      'Apply mancozeb or chlorothalonil fungicide',
      'Remove infected foliage',
      'Ensure adequate nitrogen',
    ],
    prevention: [
      'Use certified disease-free seed potatoes',
      'Rotate with non-host plants for 3 years',
      'Maintain proper nutrition',
    ],
  },
  {
    id: 'potato-late-blight',
    plant: 'Potato',
    plantIcon: '🥔',
    name: 'Late Blight',
    scientificName: 'Phytophthora infestans',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Critical',
    severityColor: '#dc2626',
    description: 'Late blight is the most destructive potato disease, capable of destroying entire fields.',
    symptoms: [
      'Water-soaked spots that expand rapidly',
      'White fungal growth on leaf undersides',
      'Brown, firm rot in tubers',
      'Foul smell from decaying tubers',
    ],
    causes: [
      'Phytophthora infestans',
      'Cool, moist weather',
      'Infected seed potatoes',
      'Windborne spores from infected fields',
    ],
    treatment: [
      'Apply metalaxyl fungicide immediately',
      'Destroy infected plants',
      'Do not store infected tubers',
    ],
    prevention: [
      'Use only certified disease-free seed',
      'Plant resistant varieties',
      'Apply preventative fungicide in wet conditions',
    ],
  },
  {
    id: 'potato-healthy',
    plant: 'Potato',
    plantIcon: '🥔',
    name: 'Healthy Potato',
    scientificName: 'Solanum tuberosum',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your potato plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Use certified seed potatoes and practice crop rotation'],
  },

  // ─── RASPBERRY ───
  {
    id: 'raspberry-healthy',
    plant: 'Raspberry',
    plantIcon: '🍓',
    name: 'Healthy Raspberry',
    scientificName: 'Rubus idaeus',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your raspberry plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Maintain good sanitation and plant spacing'],
  },

  // ─── SOYBEAN ───
  {
    id: 'soybean-healthy',
    plant: 'Soybean',
    plantIcon: '🌱',
    name: 'Healthy Soybean',
    scientificName: 'Glycine max',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your soybean plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Practice good crop rotation and field sanitation'],
  },

  // ─── SQUASH ───
  {
    id: 'squash-powdery-mildew',
    plant: 'Squash',
    plantIcon: '🎃',
    name: 'Powdery Mildew',
    scientificName: 'Erysiphe cichoracearum',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Powdery mildew appears as white powder on squash leaves, reducing photosynthesis and yield.',
    symptoms: [
      'White powdery spots on leaves',
      'Leaves turn yellow and brown',
      'Premature leaf drop',
      'Reduced fruit size and quality',
    ],
    causes: [
      'Powdery mildew fungi',
      'High humidity with moderate temperatures',
      'Poor air circulation',
      'Dense planting',
    ],
    treatment: [
      'Apply sulfur or neem oil',
      'Remove severely infected leaves',
      'Improve air circulation',
    ],
    prevention: [
      'Plant resistant varieties',
      'Space plants properly',
      'Avoid excess nitrogen fertilizer',
      'Apply preventative fungicide',
    ],
  },

  // ─── STRAWBERRY ───
  {
    id: 'strawberry-leaf-scorch',
    plant: 'Strawberry',
    plantIcon: '🍓',
    name: 'Leaf Scorch',
    scientificName: 'Diplocarpon earliana',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Leaf scorch causes dark purple spots that make leaves look scorched, reducing plant vigor.',
    symptoms: [
      'Dark purple spots on upper leaf surface',
      'Spots have brown or gray centers',
      'Leaves appear scorched',
      'Reduced fruit production',
    ],
    causes: [
      'Diplocarpon earliana fungus',
      'Warm, wet conditions',
      'Dense planting',
    ],
    treatment: [
      'Apply captan or myclobutanil fungicide',
      'Remove infected leaves',
      'Renovate plantings after harvest',
    ],
    prevention: [
      'Use certified disease-free plants',
      'Plant resistant varieties',
      'Avoid overhead irrigation',
    ],
  },
  {
    id: 'strawberry-healthy',
    plant: 'Strawberry',
    plantIcon: '🍓',
    name: 'Healthy Strawberry',
    scientificName: 'Fragaria × ananassa',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your strawberry plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Use certified disease-free plants and maintain good sanitation'],
  },

  // ─── TOMATO ─── (Add the missing ones)
  {
    id: 'tomato-septoria-spot',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Septoria Leaf Spot',
    scientificName: 'Septoria lycopersici',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Septoria leaf spot causes small circular spots that can lead to severe defoliation.',
    symptoms: [
      'Small circular spots with dark borders and gray centers',
      'Black dots in spot centers (fungal fruiting bodies)',
      'Lower leaves affected first',
      'Severe defoliation from bottom up',
    ],
    causes: [
      'Septoria lycopersici fungus',
      'Warm, wet weather',
      'Soil splash onto lower leaves',
    ],
    treatment: [
      'Apply chlorothalonil or mancozeb fungicide',
      'Remove infected leaves',
      'Mulch around plants',
    ],
    prevention: [
      'Rotate tomatoes with non-host crops',
      'Water at base of plants',
      'Space plants for good airflow',
    ],
  },
  {
    id: 'tomato-spider-mite',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Spider Mites',
    scientificName: 'Tetranychus urticae',
    type: 'Pest',
    typeColor: '#f59e0b',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Spider mites are tiny pests that cause stippling damage on tomato leaves and reduce plant vigor.',
    symptoms: [
      'Tiny yellow or white speckles on leaves (stippling)',
      'Fine webbing on undersides of leaves',
      'Leaves turn bronze or yellow',
      'Severe infestations cause leaf drop',
    ],
    causes: [
      'Two-spotted spider mites',
      'Hot, dry conditions',
      'Dusty conditions',
      'Overuse of broad-spectrum pesticides killing natural enemies',
    ],
    treatment: [
      'Spray with horticultural oil or insecticidal soap',
      'Introduce predatory mites',
      'Regular strong water spray to dislodge mites',
      'Apply neem oil',
    ],
    prevention: [
      'Keep plants well-watered',
      'Reduce dust on leaves',
      'Encourage natural predators',
      'Monitor regularly for early signs',
    ],
  },
  {
    id: 'tomato-target-spot',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Target Spot',
    scientificName: 'Corynespora cassiicola',
    type: 'Fungal',
    typeColor: '#8b5cf6',
    severity: 'Medium',
    severityColor: '#f59e0b',
    description: 'Target spot causes concentric ring lesions on leaves, stems, and fruit of tomatoes.',
    symptoms: [
      'Circular spots with concentric rings on leaves',
      'Dark brown lesions with yellow halos',
      'Sunken lesions on stems and fruit',
      'Severe defoliation in humid conditions',
    ],
    causes: [
      'Corynespora cassiicola fungus',
      'High humidity and leaf wetness',
      'Overcrowded plants',
    ],
    treatment: [
      'Apply chlorothalonil or mancozeb fungicide',
      'Remove infected leaves',
      'Improve air circulation',
    ],
    prevention: [
      'Rotate crops',
      'Avoid overhead watering',
      'Space plants properly',
      'Apply preventative fungicide',
    ],
  },
  {
    id: 'tomato-yellow-leaf-curl',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Yellow Leaf Curl Virus',
    scientificName: 'Tomato yellow leaf curl virus (TYLCV)',
    type: 'Viral',
    typeColor: '#6366f1',
    severity: 'High',
    severityColor: '#ef4444',
    description: 'Tomato yellow leaf curl virus causes stunting, leaf curling, and reduced fruit production.',
    symptoms: [
      'Leaves curl upward and inward',
      'Yellow margins on leaves',
      'Severely stunted growth',
      'Reduced fruit set and size',
    ],
    causes: [
      'Tomato yellow leaf curl virus',
      'Spread by whiteflies (Bemisia tabaci)',
      'Infected transplants',
    ],
    treatment: [
      'No cure - remove infected plants',
      'Control whitefly vectors',
      'Use reflective mulches to repel whiteflies',
    ],
    prevention: [
      'Use virus-resistant varieties',
      'Exclude whiteflies with row covers',
      'Remove infected plants immediately',
      'Control weeds that harbor whiteflies',
    ],
  },
  {
    id: 'tomato-healthy',
    plant: 'Tomato',
    plantIcon: '🍅',
    name: 'Healthy Tomato',
    scientificName: 'Solanum lycopersicum',
    type: 'Healthy',
    typeColor: '#22c55e',
    severity: 'None',
    severityColor: '#22c55e',
    description: 'Your tomato plants appear healthy with no disease symptoms.',
    symptoms: ['No disease symptoms detected'],
    causes: ['Plants are well-maintained and disease-free'],
    treatment: ['Continue regular maintenance'],
    prevention: ['Practice good garden sanitation and crop rotation'],
  },
]

// Helper functions
export const getByPlant = (plantName) =>
  diseases.filter(d => d.plant.toLowerCase() === plantName.toLowerCase())

export const getById = (id) =>
  diseases.find(d => d.id === id)

export const getAllPlants = () =>
  [...new Set(diseases.map(d => d.plant))]

export const getByType = (type) =>
  diseases.filter(d => d.type.toLowerCase() === type.toLowerCase())

export const getAllTypes = () =>
  [...new Set(diseases.map(d => d.type))]